[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/drinks/*"
  to = "/.netlify/functions/drinks"
  status = 200
  force = true

[[redirects]]
  from = "/api/drinks"
  to = "/.netlify/functions/drinks"
  status = 200
  force = true
